### ISSUE TITLE
Consider smallcaps LINE instructions

### ISSUE THREAD

**Issue by MostAwesomeDude** [monte-language/typhon#105]
LINE would be a way for the VM to know the correspondence between the VM's current state and the original source files. Its main use would be in debugging, both via interactive debuggers and also tracebacks.

**Comment by dckc** [comment]
duplicate of #47?

**Comment by MostAwesomeDude** [comment]
No, we can advance progress on this without actually working on any sort of interactive debugger.

**Comment by MostAwesomeDude** [comment]
Span information is available to the VM now. It's even finer-grained than line information.
