### ISSUE TITLE
.mt suffix competes with Mathematica

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#109]
github thinks 49% of this project is written in Mathematica

**Comment by dckc** [comment]
I think I asked about this before and the answer was "too bad" but I like to see such decisions explicit in the issues list.

**Comment by MostAwesomeDude** [comment]
We can fix Github, although I don't think that that work is being tracked anywhere.

**Comment by dckc** [comment]
fix github? i.e. convince it that .mt doesn't always mean Mathematica?

**Comment by dckc** [comment]
Is this a dup of https://github.com/monte-language/monte/issues/44 ? In which repo does this issue belong?

**Comment by MostAwesomeDude** [comment]
Closing in favor of upstream PR github/linguist#3062.
