### ISSUE TITLE
M.callWithPair increasingly incorrectly named

### ISSUE THREAD

**Issue by MostAwesomeDude** [monte-language/typhon#115]
`M.callWithPair` is advertised in two arities, `.callWithPair/2` and `.callWithPair/3`. In the latter case, the argument isn't used. The correct usage appears to be `M.callWithPair(obj, message)`, where `message` is a standard `[verb :Str, args :List, namedArgs :Map]` message.

(ERights: http://wiki.erights.org/wiki/Object_E#callWithPair.2F3)

Since we have no usage of this method at all in the core, I suggest immediately removing `.callWithPair/3`. I also want to consider a `Triple` guard to be able to cleanly express the type of messages, `def Message := Triple[Str, List, Map]`, and to rename this method to `M.callWithTriple`.

**Comment by MostAwesomeDude** [comment]
Oh, consider whether `M.call/3` should also take a dirt nap.

**Comment by MostAwesomeDude** [comment]
Oh, and this already all happened and the new blessed verb is `M.callWithMessage/2`. I think that I've gotta update the docs too.

**Comment by erights** [comment]
"a dirt nap"?

**Comment by dckc** [comment]
"to die and be buried" -- [source](http://idioms.thefreedictionary.com/take+a+dirt+nap)
