### ISSUE TITLE
Method .empty/0 for collections

### ISSUE THREAD

**Issue by MostAwesomeDude** [monte-language/typhon#123]
I am tired of writing `if (someList.size() == 0)` over and over. I would like to instead write `if (someList.empty())`. Thoughts?

**Comment by erights** [comment]
Sounds fine to me. I can't think of any good reason I omitted this from E.

**Comment by MostAwesomeDude** [comment]
Agreed, it's usually a simpler case analysis that doesn't require a full examination.

Current discussion:
* As usual, we have a verb bikeshed. Should we use `.isEmpty()` instead? It was noted that `.empty()` could be considered an imperative (mutable) action. We could also choose to embrace `.clear()` as the way to discard all of the items in a container.
* This should go on `List`, `Set`, and `Map`.
