### ISSUE TITLE
Anonymous slots

### ISSUE THREAD

**Issue by MostAwesomeDude** [monte-language/typhon#131]
Should this be legal, and if so, what are the semantics?

    def m := ["&name" => &42, "&&name" => &&42]

**Comment by dckc** [comment]
why would it be legal? What experience motivates this change?

Hint: if the only examples that come to mind are foo/bar/baz examples, let's not.

**Comment by dckc** [comment]
Oh... I see Simon and Dash are leaning against this one in any case.

**Comment by MostAwesomeDude** [comment]
There are several use cases in the prelude.

Closing as rejected; we won't be adding this to the language.
