### ISSUE TITLE
Typhon Should Not `Install` if Build Fails

### ISSUE THREAD

**Issue by justinnoah** [monte-language/typhon#137]
When something, even as simple as:
```
Problem: "makeMtJSON" in the lexical scope of <eval>$_$new_project does not have a guard implying DeepFrozen, but FinalSlot[Any]
In <DeepFrozen>.audit(<Audition>):
In <_>.run([[["lib/json" => ["JSON" => <JSON>, "js…):
```
occurs, Typhon should short circuit the build process. The code is bunk, why complete the process?

**Comment by dckc** [comment]
progress: a0f47ee
maybe even fixed, but I haven't verified

**Comment by MostAwesomeDude** [comment]
We compile modules individually, now, and we'll eventually compile executables individually. The build does stop if a single module fails.
