### ISSUE TITLE
Containers should have a .empty() method

### ISSUE THREAD

**Issue by MostAwesomeDude** [monte-language/typhon#138]
I guess that we don't have an issue for this yet!

**Comment by MostAwesomeDude** [comment]
Doing `.isEmpty() :Bool` since that matches our predicate methods on other builtins.

**Comment by erights** [comment]
Glad to see the name `isEmpty` rather than `empty`. `empty` can also be read as an imperative, to empty out (or clear) the container.

**Comment by MostAwesomeDude** [comment]
@erights My thoughts precisely.
