### ISSUE TITLE
Cooperative inheritance pattern

### ISSUE THREAD

**Issue by MostAwesomeDude** [monte-language/typhon#159]
This syntax is not correctly expanded:

    object child extends makeParent(child):
        to things():
            return 5

The `child` name isn't created with a promise and resolver, but is instead created directly; this causes a define-before-use. Fixing this would enable cooperative inheritance.

The idea is that the parent is given a reference to the child, allowing the loop to be tied:

    def makeParent(self):
        return object parent:
            to add():
                return self.things() + 5

(Yes, I know that this is not a good example. Better examples are welcome.)

**Comment by washort** [comment]
https://github.com/monte-language/typhon/commit/a63a5de5ac5894574f68354fdf4e543730d110f6
