### ISSUE TITLE
`for x in xs:` gives unhelpful syntax error

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#171]
Given the python heritage, `expected DEDENT got IDENTIFIER` is not maximally helpful for forgetting parens in:

```
for expr in examples:
    ...
```

**Comment by MostAwesomeDude** [comment]
Parser upgrade incoming:

    ▲> m`for x in xs {}`
    Parse error: Exception: expected '(' for start of for-expr iterable, got "IDENTIFIER"
