### ISSUE TITLE
import does synchronous I/O

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#18]
Isn't all I/O in monte supposed to be async?

monte import() calls python's open().read() synchronously.
https://github.com/monte-language/typhon/blob/master/typhon/importing.py#L72

Any particular reason not to use something like ES6 modules and [System.js](https://github.com/systemjs/systemjs)?

**Comment by MostAwesomeDude** [comment]
Importing should probably be async, yes. This is a hint for one of two directions.

One way is to make all imports async and require a send and when-expr to access them. This sounds tedious but correct.

Another way might be to make imports not functions, but syntax, and compile modules at load time into graphs of imports. This would be tedious too. Hm.

**Comment by dckc** [comment]
The ES6 module design has both: import syntax and async import functions.

**Comment by MostAwesomeDude** [comment]
The package loader uses async I/O to read in module files. I'd say that we've got this fixed.

**Comment by dckc** [comment]
\o/
