### ISSUE TITLE
import() does not admit static analysis

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#19]
One motivation for dedicated syntax for modules (in addition to library routines) is static analysis.

ref:
 - [ECMAScript 6 modules: the final syntax](http://www.2ality.com/2014/09/es6-modules-final.html) 2014-09-07

**Comment by MostAwesomeDude** [comment]
Yeah. We've talked about similar ideas in the past. One possibility is that import time is a magical fairyland where the scope is full of promises and most computation is suspended based on import() invocations. This sounds really nasty to get right, though.

ES6 exports might be something that we want. The current "run the module to the end" system isn't bad but is definitely misleading in terms of what's statically visible.

Note that, in all cases, import() currently is still a function with no dedicated syntax, which means that normal static analysis for name usage works fine.

**Comment by dckc** [comment]
What I mean by "does not admit static analysis" is that you can't tell, statically, what modules are imported in order to provide them without when() -> ... ; i.e. you can't do the sort of compile step you alluded to in #18 . I suppose I should not have filed separate issues.

**Comment by MostAwesomeDude** [comment]
The loader currently constructs a module configuration graph and can dump it with the ``dot`` subcommand. Our module system definitely permits us to examine a module by calling ``.dependencies/0`` as a separate step from instantiating the module.

I am happy to report that this is fixed.
