### ISSUE TITLE
`extends` should generate Miranda _printOn

### ISSUE THREAD

**Issue by MostAwesomeDude** [monte-language/typhon#21]
Otherwise it gets passed onward to the extended object, creating misleading tracebacks when things invariably go wrong.

**Comment by MostAwesomeDude** [comment]
Unclear whether this should extend to other Miranda objects; discussion is required.

**Comment by washort** [comment]
https://github.com/monte-language/typhon/commit/9a8be117ccb0f11a0eea05df943930cea3bfc524
