### ISSUE TITLE
low-level async I/O: try libuv

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#30]
use libuv, 'cause Corbin said he'd do it

dash> simpson: the crucial factor to me is that we can drop libuv at any point
 simpson: so at worst we're deferring some work, at best skipping a lot of it
 the APIs aren't gonna change

**Comment by MostAwesomeDude** [comment]
The uv branch tracks this work.

**Comment by dckc** [comment]
lots of good progress; e.g. eeddaa2639ca811400bd562a1226fcdde4f545d4

**Comment by MostAwesomeDude** [comment]
Success; merged.
