### ISSUE TITLE
explicit authority in top-level scripts

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#33]
I suggest loading scripts in the safe scope and then explicitly passing authority (a object with methods corresponding to the unsafe scope) to the main function (the last expression in the script).

Scripts currently load in the unsafe scope. So the only way to use normal least authority ocap patterns is to put most of the code in a secondary module and load it from a minimal script. (For example, see the current [taste of monte](http://monte.readthedocs.org/en/latest/intro.html#a-taste-of-monte)) This means programmers have to go out of their way to use least authority patterns and it facilitates ordinary ambient authority style. Not very monte-like.

**Comment by dckc** [comment]
Better yet: let scripts serve as either modules or scripts (just like python) by looking for the `=> main` entry of a map exported from a module.

**Comment by MostAwesomeDude** [comment]
Post-module-rework. All modules which export ``main`` are scripts. ``main`` will be passed ``run(env :Map)`` and should return something which coerces to Int and describes how successful the execution went.

**Comment by MostAwesomeDude** [comment]
Merged the new module work, which implements this.
