### ISSUE TITLE
equivalent of `from m1 import f2`?

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#42]
In "a taste of monte", I've got:

```
imports
exports (main)

...

def main(=> makeTCP4ServerEndpoint, => currentProcess) as DeepFrozen:
    def [=> strToInt] | _ := import.script("lib/atoi")
```

If I hoist the atoi import to the top level, I get `In throw.Atom(run/1) ["\"strToInt\" in the lexical scope of web1.ty$_$main does not have a guard implying DeepFrozen, but FinalSlot[Any]"]`. *Gesundheit*.

**Comment by dckc** [comment]
Corbin gave me one clue in the right direction:

```
def [=> strToInt :DeepFrozen] | _ := import.script("atoi")
```

This works if I make my own version of `atoi.mt` that adds `... as DeepFrozen` to the declaration of `strToInt`.

**Comment by MostAwesomeDude** [comment]
Current import syntax is documented [here](http://monte.readthedocs.org/en/latest/modules.html). I am happy to say that this example looks pretty good right now:

    import "lib/atoi" =~ [=> strToInt :DeepFrozen]
    exports (main)
