### ISSUE TITLE
debugger support in smallcaps

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#47]
an idea: when compiling to smallcaps, support a debug mode where expression spans are consulted and each time the line number increases, write a LINE noop opcode that records the file and line number.

Then support a debug mode for interpreting smallcaps that takes a set of breakpoints as an argument; executing the LINE opcode checks whether a breakpoint is hit.

Am I just remembering how python works? Looks like it, roughly.

**Comment by MostAwesomeDude** [comment]
Span information is available in tracebacks now, and obsoletes all of this.
