### ISSUE TITLE
monte nix builds don't have increasing versions

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#65]
The usual approach to keeping up to date would be `nix-channel --update; nix-env -u typhon`, but the monte nix builds don't have increasing versions.

I documented a work-around in [Getting Started][1].

[1]: https://github.com/monte-language/monte/wiki/Getting-Started

**Comment by MostAwesomeDude** [comment]
Hm, just double-checking before I try researching this one again, doesn't ``$(nix-channel --update; nix-env -i mt)`` work?

**Comment by dckc** [comment]
`nix-env -i mt` works for the initial install, but to update an installed package, you're supposed to use `nix-env -u`. This only works if the version number increases. Otherwise, you have to add the '--leq' flag.

I just tested `nix-env -i mt` when it's already installed; I'm not quite sure what it does:

```
$ nix-env  -i mt
warning: there are multiple derivations named ‘mt’; using the first one
replacing old ‘mt’
installing ‘mt’

```

**Comment by MostAwesomeDude** [comment]
That should replace whatever was `mt` with whatever your channel says `mt` should be. It'll do an upgrade. It'll do a downgrade. It'll do a no-op.

**Comment by dckc** [comment]
Are you saying that `nix-env -i mt` will do an upgrade? How would people learn that? Is it documented?

https://nixos.org/wiki/Install/remove_software#How_to_update_installed_software says to use `nix-env -u`.

**Comment by dckc** [comment]
I can't figure out how to add the `wontfix` label; perhaps I don't have the relevant magic powers.


dash> DanC_: AFAICT versioning for nix derivations has to be pretty manual, tying version numbers to specific source revisions
 DanC_: so, not something we could get out of a channel that always builds git HEAD
