### ISSUE TITLE
Generalized functional objects

### ISSUE THREAD

**Issue by MostAwesomeDude** [monte-language/typhon#66]
Adopt the following sugar syntax:

```
def name.verb(x, y, => this, => that):
    body
```

Which is sugar for:

```
object name:
    to verb(x, y, => this, => that):
        body
```

**Comment by dckc** [comment]
care to elaborate on motivation?

**Comment by MostAwesomeDude** [comment]
Motivation: Many times, we want objects to respond to a single method, as if they were functions, but wish to choose a verb that is not "run". All of those times are times where a single protocol, with a single method, is implemented. Some examples:

* Several safe scope objects, like `_makeVerbFacet`, only implement a single verb
* The tube subsystem has an interface with a single ``.unpause/0`` method

Admittedly, these are not common cases.

**Comment by MostAwesomeDude** [comment]
We've agreed to make this change. We'll need to document it, and also figure out a plan of attack on the parser, expander, and AST.

**Comment by dckc** [comment]
I remain somewhat skeptical. In working on the railroad diagrams, I found that the parser was already squirrelly enough, and much of the squirrelliness was because of the syntax itself, not just poor coding.

**Comment by MostAwesomeDude** [comment]
Documented the change to the language's grammar in monte-language/monte@c4d9ad6.
