### ISSUE TITLE
don't recompile if X.mast newer than X.mt

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#70]
Automatic compilation of .mt to .mast in `mt run X` is nice, but with each module taking several seconds (and making lots of noise) to compile, unnecessary compilation is a real downer.

**Comment by MostAwesomeDude** [comment]
Scoping this to just `mt run`; fixing this for Nix is intractable right now.

**Comment by dckc** [comment]
This seems to work now.

Perhaps it was fixed in 771d79d26dd0ff51cb5ec680a52913fce0f4fabe?
