### ISSUE TITLE
Monte Developer Edition 2016 release

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#74]
Monte 2016 Release Requirements
- [ ] Packaging is sufficiently robust to allow third-party development
  - [ ] ~~Command to add github repos as dependencies~~ (postponed: #108)
  - [x] Command to generate .nix file for checkin
  - [x] Command to instantiate repl with package available, or launch mainpoint
  - [x] Nix must be incantable as a subprocess (#26)
  - [x] Nix expressions are available for building packages
- [x] Documentation should have only one narrative for developers (and possibly another for marketing purposes)
- [x] [Web presence](http://www.monte-language.org/) (single Web page)
- [x] developer tools:
  - [x] flymake/syntastic integration with linter
  - [x] atom/emacs/vim syntax highlighting for current syntax

Non-Requirements
- Syntax is not frozen yet
- montepool not in scope
- captp/amp not in scope
- native debugger
- checkpointing in all primitive ops (especially exponentiation)
- per-vat heaps
- TLS tunnel commands (stunnel, hitch)

_based on references from IRC chat March17_

**Comment by MostAwesomeDude** [comment]
Update: We have convinced the linter to interoperate with emacs and vim.

**Comment by dckc** [comment]
emacs and vim linter support is cool... but is it sufficiently documented to call it done?

**Comment by dckc** [comment]
I wonder if "Command to add github repos as dependencies" is critical path.

Aside from that, this ticket comes down to the web presence, which I suppose makes sense.

**Comment by dckc** [comment]
Are release announcement drafts being kicked around? This issue would be the most convenient place for me.

**Comment by justinnoah** [comment]
@MostAwesomeDude [re: emacs/vim linter] how is this achieved? I'd like to add support for Atom.

**Comment by dckc** [comment]
I have never used it, but Atom support is there: http://monte.readthedocs.io/en/latest/intro.html#atom

**Comment by dckc** [comment]
I suppose we should have closed this issue around June 1:

> Monte is officially out of steath mode. Tell your friends: http://www.monte-language.org/ 
  -- https://twitter.com/corbinsimpson/status/738016229399494657

**Comment by justinnoah** [comment]
Ha, I initially created that too. Though it is currently broken.
