### ISSUE TITLE
Change quasiliteral expansion from "__quasiParser" to "``"

### ISSUE THREAD

**Issue by washort** [monte-language/typhon#76]
We can build it, we have the technology.

**Comment by MostAwesomeDude** [comment]
We have three core quasiparsers: `simple`, `m`, and `b`.

**Comment by dckc** [comment]
Why be arbitrarily different from E in this way?

**Comment by washort** [comment]
These objects have to be referred to by name, at least to import them. This form of name seems more obvious to me and there's no reason to retain the E double-underscore convention.
