### ISSUE TITLE
Implement Semitransparent

### ISSUE THREAD

**Issue by washort** [monte-language/typhon#87]
Semitransparent should behave like Transparent, but only reveal contents to the holder of the Semitransparent unsealer -- this will allow objects to reveal their contents to the equalizer but not make them public.

The initial motivation for this feature is making problems compare same when their messages are the same.

**Comment by MostAwesomeDude** [comment]
Here's a more specific use-case:

```monte
def problemSet := [].asSet().diverge()
for input in (inputs):
    try:
        f(input)
    catch problem:
        problemSet.include(problem)
```

Trying to run a function across some span of inputs and catching all of the distinct problems is admittedly contrived. We could also use this to implement e.g. equality for secret keys.

**Comment by washort** [comment]
VerbCurry and SendCurry would both benefit from this. They should pass DF if their wrapped object does, but they must not expose the wrapped object.

**Comment by dckc** [comment]
Ah... this explains part of my letrec issue #179

**Comment by washort** [comment]
https://github.com/monte-language/typhon/commit/ad341e8eb643fcbda547d129e4e5e188b8b9f4db
