### ISSUE TITLE
Separate `mafia` repo and document library use

### ISSUE THREAD

**Issue by washort** [monte-language/typhon#88]
The mafia game is referenced in the tutorial and should be used as an example of how to interact with a third-party library.

**Comment by dckc** [comment]
I made a repo: https://github.com/dckc/mt-mafia

Perhaps you could fix up the README and/or other monte docs to discuss interacting with a library etc.? And add a license?

**Comment by dckc** [comment]
I made a repo in our organization: https://github.com/monte-language/mt-mafia

and I did LICENSE=ASL 2.0

**Comment by washort** [comment]
some bugs in the packaging stuff kept mt-mafia from working, fixed in https://github.com/monte-language/typhon/commit/ae40ff473dc082d5a114ecef692f23613f21d813

**Comment by dckc** [comment]
`mt run mafiabot` is building a typhon vm. Is this as-designed?

I seem to recall something about one mt with nix fetch tools and one without, but I'm not sure why, after I can `mt repl`, I need another vm for `mt run`.

**Comment by dckc** [comment]
dash wrote docs in b517c9ad48211c46b931accf72ca1d8c6909ded5

This is fixed, but I don't seem to have enough magic powers to close it.

**Comment by MostAwesomeDude** [comment]
Huh, that's strange. Anyway, I have such powers!
