### ISSUE TITLE
sort out license text

### ISSUE THREAD

**Issue by washort** [monte-language/typhon#89]
Put all the license things where they go.

**Comment by dckc** [comment]
simpson> dash, DanC, mythmon, runciter: We're gonna do an AUTHORS file on Typhon, for issue #89.

OK by me.

I'm also OK with CC0 on my contributions to the docs.

I'm also supportive of other options that get this resolved quickly.

**Comment by washort** [comment]
+1, copyright assignment is a net negative

**Comment by MostAwesomeDude** [comment]
Docs have been CC0'd. We just gotta clean up the license annotations on this repository.

**Comment by dckc** [comment]
What would it look like cleaned up? I'm willing to do some administrative work, but I'm not sure what it should look like.
