### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by justinnoah** [monte-language/typhon#9]
When building with `python -m rpython -Ojit main` I ran into a missing headers error. Noting that libffi headers are needed may be useful.

I am not sure if this is the same case with `python -m rpython -O2 main`

**Comment by MostAwesomeDude** [comment]
At this point, the build process is very different from how it used to be, and our CI system ensures that builds are complete. Perhaps some docs need to be updated?

**Comment by dckc** [comment]
As I wrote in [Getting-Started](https://github.com/monte-language/monte/wiki/Getting-Started), The *How To Monte* section of the typhon README doesn't seem to keep up with development. Until things settle down, I'd prefer that the typhon README just pointed to that wiki page. That lets the users keep it up to date and report experience.

**Comment by MostAwesomeDude** [comment]
The build instructions are up-to-date.
