### ISSUE TITLE
standalone packages/tarballs for release

### ISSUE THREAD

**Issue by washort** [monte-language/typhon#90]
Packages with no Nix dependency will be nice for those just testing it out.

**Comment by MostAwesomeDude** [comment]
I can produce Typhon and the prelude in a tarball, but providing an ``mt`` command to those without Nix is impractical. Instead, let us provide instructions for installing Nix and also for setting up NixOS in a VM.

The reasoning is that, no matter which method we pursue, our binaries will still point to ``/nix/store``, so refusing to curlbash Nix is not really dodging the creation of the Nix store, which is necessary for us and also the bulk of why Nix has to be trusted. IOW, why would you run my binaries if you don't trust Nix's binaries?

**Comment by dckc** [comment]
Yes, let's provide instructions on installing nix. Does https://github.com/monte-language/monte/wiki/Getting-Started suffice?

The lack of proper package versions (#65) is kinda painful. Add it to this milestone?

**Comment by dckc** [comment]
nix has [debian-build.nix][]  for making .deb packages. It's straightforward to use provided your Makefile has `install` and `dist` targets, but for monte and typhon, that info is only in .nix files, and it's spread between 3 packages. Perhaps it could be refactored...

[debian-build.nix]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/release/debian-build.nix

**Comment by dckc** [comment]
In [release.nix][], we can see an example of making source and binary tarballs. The binary tarball seems to do a normal nix build, add [install-nix-from-closure.sh][] to the result, and then run tar with a bunch of `--transform` arguments. I'm having trouble understanding to what extent this would work for us.

[release.nix]: https://github.com/NixOS/nix/blob/master/release.nix
[install-nix-from-closure.sh]: https://github.com/NixOS/nix/blob/master/scripts/install-nix-from-closure.sh

**Comment by dckc** [comment]
I'd be content to see this postponed to a later milestone.

It would be nice to have, but it doesn't look straightforward.

**Comment by MostAwesomeDude** [comment]
I think that we are set on this; we have the `mtDocker` expression for generating this. Or do we need more docs?

**Comment by dckc** [comment]
We went with docker and nix for the June 1 release.
http://monte.readthedocs.io/en/latest/intro.html#quick-start-docker-image

I suggest closing this issue. (It seems I'm authorized to close monte issues but not typhon issues. Which is fine with me.)

**Comment by MostAwesomeDude** [comment]
Yeah, we no longer need this issue.
