### ISSUE TITLE
invalid AST produced by montec

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#92]
attached find a .mt file and the .mast file that montec compiled it to. typhon won't load it: `Error: "Couldn't load invalid AST"`

[bad-mast.zip.zip](https://github.com/monte-language/typhon/files/212279/bad-mast.zip.zip)

version info: `/nix/store/9f2yjgkfhwgd4b99573gnvnxxj7ssd50-mt/bin/mt`

**Comment by MostAwesomeDude** [comment]
This was tracked down to Typhon's compiler being unable to miss a double-defined name; the Monte verifier failed to catch this one.

So we should fix the verifier, probably.

**Comment by MostAwesomeDude** [comment]
We did fix the verifier, apparently.
