### ISSUE TITLE
mac port: nix, homebrew, ...

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#96]
Here's hoping...

**Comment by dckc** [comment]
looks like translation mostly works but it won't link:

```
[translation:info] Translating target as defined by main
...
[platform:Error] ld: library not found for -lnsl
```

details in [full log](https://gist.github.com/dckc/b498cc76006046daa5549d4f51a61e3d)

**Comment by travisbhartwell** [comment]
I am able to install on OS X successfully.   I'm on OS X 10.11.4.

I have the Typhon master branch checked out, which as of today is commit 2b2aa627971f13a811144a0318062e38f875f2aa.

I have Nix installed and am using the nixpkgs-unstable channel, which I just updated, so I'm at NixOS/nixpkgs-channels@9445bb25fc77f8e53c5fd024c9609d8a3b8590cc

I was able to successfully install Typhon using this, from the Typhon checkout directory:
```
nix-env -f . -iA mt
```

**Comment by travisbhartwell** [comment]
I apologize, I forgot that I had a couple of small changes that I had to make to get this to work:

```
~/Misc/typhon$ git diff
diff --git a/nix/vm.nix b/nix/vm.nix
index 4206933..fa27037 100644
--- a/nix/vm.nix
+++ b/nix/vm.nix
@@ -2,8 +2,10 @@
 
 # $ nix-prefetch-hg https://bitbucket.org/pypy/pypy
 let pypySrc = fetchzip {
-    url = "https://bitbucket.org/pypy/pypy/downloads/pypy-5.0.0-src.tar.bz2";
-    sha256 = "1hxjhm66081hnhdkf0fifswc9js9qi88zyy7pfpcwlxl029sddj0";
+    # url = "https://bitbucket.org/pypy/pypy/downloads/pypy-5.0.0-src.tar.bz2";
+    url = "https://bitbucket.org/pypy/pypy/get/release-5.x.tar.bz2";
+    sha256 = "1gz41yag740mizs5d5m9y223hq8c5ib6791i0qxylxrgl7l3k2lc";
+    # sha256 = "1hxjhm66081hnhdkf0fifswc9js9qi88zyy7pfpcwlxl029sddj0";
   };
   optLevel = if buildJIT then "-Ojit" else "-O2";
 in
diff --git a/typhon/ruv.py b/typhon/ruv.py
index 492c6fb..6be1b0f 100644
--- a/typhon/ruv.py
+++ b/typhon/ruv.py
@@ -69,7 +69,7 @@ def envPaths(name):
 eci = ExternalCompilationInfo(includes=["uv.h"],
                               include_dirs=envPaths("TYPHON_INCLUDE_PATH"),
                               library_dirs=envPaths("TYPHON_LIBRARY_PATH"),
-                              libraries=["nsl", "rt", "uv"])
+                              libraries=["uv"])
 
 
 class CConfig:
```

The change to the pypy version included is necessary to pull in a change that fixes building on OS X.

The `ns1` and `rt` libraries aren't necessary on OS X, so they were elided in `ruv.py`.

I'm not sure how these changes need (or can be) incorporated in the Typhon code.

**Comment by cdunklau** [comment]
This is in PR #122 but I'm reproducing it here for posterity:

On OS 10.11.6, I received the following error:

```
[platform:Error] ld: library not found for -lrt
[platform:Error] clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
```
Full failing build output is attached:
[darwin-with-rt-build.txt](https://github.com/monte-language/typhon/files/417199/darwin-with-rt-build.txt)

Per @MostAwesomeDude's suggestions, I removed rt from the libs for Darwin, and the build succeeded.

**Comment by MostAwesomeDude** [comment]
I'm actually gonna close this. We all but support Darwin now.
